import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import ClientOnly from "@/components/ClientOnly";
import Navbar from "@/components/Navbar/Navbar";
import ToasterProvider from "@/providers/ToasterProvider";
import getCurrentUser from "@/actions/getCurrentUser";
import ModalsProvider from "@/providers/ModalsProvider";
import Listings from "@/components/Listings";

const font = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TrauBall App",
  icons: "/images/logo.jpg",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={font.className} suppressHydrationWarning>
        <ClientOnly>
          <ToasterProvider />
          <ModalsProvider />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        <Listings />
        <div className="pb-20 pt-28">{children}</div>
      </body>
    </html>
  );
}
